[green_agent]
agentbeats_id = "019bc5a9-3d03-7553-985f-ea34c0123801"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}", LOG_LEVEL = "INFO" }

# gpt-4o only (running separately to get second model results)
[[participants]]
agentbeats_id = "019c185a-22a9-7ab0-b0bf-289dd069b3e4"
name = "gpt-4o"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", AGENT_MODEL = "openai/gpt-4o" }

[config]
domain = "hospitality"
max_steps = 20
num_tasks = 1
agent_llm = "anthropic/claude-3-5-sonnet-20241022"

# trigger
# fixed
# v2 images
# entrypoint fix
# white cmd fix
# all params
# curl fix
# agentbeats format
# amd64 rebuild
