[green_agent]
agentbeats_id = "019bc5a9-3d03-7553-985f-ea34c0123801"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}", LOG_LEVEL = "INFO" }

# o4-mini
[[participants]]
agentbeats_id = "019bc5eb-d64b-7083-8fc7-eb44d59786f0"
name = "o4-mini"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", AGENT_MODEL = "openai/gpt-4o-mini" }

# gpt-4o
[[participants]]
agentbeats_id = "019c185a-22a9-7ab0-b0bf-289dd069b3e4"
name = "gpt-4o"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", AGENT_MODEL = "openai/gpt-4o" }

[config]
domain = "hospitality"
max_steps = 20
num_tasks = 1
agent_llm = "anthropic/claude-3-5-sonnet-20241022"

# trigger
# fixed
# v2 images
# entrypoint fix
# white cmd fix
# all params
# curl fix
# agentbeats format
# amd64 rebuild
